### ISSUE TITLE
Facial Expressions not applied

### ISSUE THREAD

**Issue by arborslay** [christofsteel/herosaver#1]
Changing facial expressions on the site don't affect the exported STL. The geometry of the model in the preview does actually change (not in shaders). Would also like to have an option to export base as mounts and base items don't export currently (if possible).

**Comment by JookieBoi** [comment]
> I two would support this, maybe the base could be exported as a separate file?

are you able to still do this? i need some help finding the stl file if possible

**Comment by christofsteel** [comment]
Hi,
in my tests, the facial expressions are exported. They are not as clear as in the preview, but at least slightly altered.
In regards to the bases you have two options:
* I personaly just use a base I found on thiniverse. This works great
* The script searches for biggest child object and stores its index in `max_obj`.
`var objs = CK.activeCharacter.threeObj.children;
    var max_obj = 0;
    var i;
    for(i in objs) {
        if (objs[i].children.length > objs[max_obj].children.length) {
            max_obj = i;
        }        
}`
and then converts this child object to an stl file
`var stlString = exporter.parse(CK.activeCharacter.threeObj.children[max_obj])`
You could manually set the index `max_obj` to find the base or the mount.

On another note, I will not maintain this project anymore. This project started because no stl export from heroforge was available. Now a affordable stl export is available (10$) and I encourage everyone to buy the files. These are much more high detailed than the files generated with my clumsy script, include mount and base ;)

**Comment by christofsteel** [comment]
Just updated the readme. With a bit of manual work, you can now export the mount.

**Comment by JookieBoi** [comment]
Oh wow. Thanks so much.

Is there a reason why it's not a direct copy of the model. Is there a way
to improve the model so its more rounded in certain parts?

I'm new to this!

**Comment by JookieBoi** [comment]
ok, i've tried it and it works thanks!

Is there a way to capture the figure and the mount at the same time? It's
not a problem as such, I have a way to combine two stls if not.

**Comment by christofsteel** [comment]
Exporting of the mount and base is now included in the script :)
