### ISSUE TITLE
Rotation is off

### ISSUE THREAD

**Issue by TeaWithLucas** [christofsteel/herosaver#2]
I don't think its intentional, but the rotation is off by 90 degrees in the x and z axis

**Comment by christofsteel** [comment]
Yes, I noticed that. I also think the faces in the stl-file are inside out. But since it is very easy to rotate a figure and no slicer complains about the faces being inside out, this is a wontfix (for now)...

I think if you fiddle around with the x y and z values in the export, this should be fixable, but I currently do not have the time for that.

**Comment by TeaWithLucas** [comment]
I think this a decent implementation of this:
https://github.com/christofsteel/herosaver/pull/10
